#
# HOLOCRON CONFIGURATION FILE.  PLEASE DO NOT FORGET
# TO CHANGE THE SETTINGS BELOW FOR YOURSELF. ALL THE
# SETTINGS ARE COMMENTED FOR EASY CHANGES.
#
# YOU CAN REMOVE UNNECESSARY SETTINGS FROM THIS FILE.
# IN THIS CASE DEFAULT SETTINGS WILL BE USED.
#

# Here is a blog credentials. You should change it
# on your own way.
sitename:    Obi-Wan Kenobi
siteurl:     http://obi-wan.jedi
author:      Obi-Wan Kenobi

# The content will be parsed using this encoding.
encoding: utf-8

# TODO: add option that enable relative or absolute urls

# Here is a paths for user's folders. It's ok if you
# don't want to change this settings.
paths:
   content:    ./
   output:     _build/
   theme:      _theme/

# This node is sent directly to the jinja2 template. It's a good
# place to keep theme-specific settings. So no it keeps deafult
# theme settings.
theme:
   navigation: !!pairs
      - /about:      /about/
      - /feed:       /feed/

   # TODO: implement 'Fork me on GitHub' feature

converters:
   enabled: [markdown]

   markdown:
      extensions: [codehilite, extra]

generators:
   enabled: [sitemap, feed]

   feed:
      save_as: feed.xml
      posts_number: 5

commands:
   serve:
      host: '0.0.0.0'
      port: '5000'
