dist: xenial
language: python
python: "3.7"
cache: pip

install:
  - python -m pip install tox codecov

script:
  - tox
  - codecov --env TOXENV

stages:
  - name: lint
  - name: test
  - name: docs
  - name: pypi
    if: tag IS present

jobs:
  include:
    - stage: lint
      env: TOXENV=pre-commit
      python: "3.7"

    - stage: test
      env: TOXENV=py36
      python: "3.6"

    - stage: test
      env: TOXENV=py37
      python: "3.7"

    - stage: test
      os: windows
      language: sh
      env: TOXENV=py37
      before_install:
        - choco install python3
        - export PATH="/c/Python37:/c/Python37/Scripts:$PATH"

    - stage: test
      os: osx
      language: sh
      env: TOXENV=py37
      before_install:
        - brew update && brew upgrade python3

    - stage: docs
      env: TOXENV=docs
      script: skip
      install: skip

    - stage: pypi
      before_deploy:
        - pip install poetry
        - poetry config http-basic.pypi $PYPI_USERNAME $PYPI_PASSWORD
        - poetry build
      deploy:
        provider: script
        script: poetry publish
      install: skip
      script: skip

  allow_failures:
    - os: windows
